{% set version = "2023.2.3" %}
package:
  name: intake-pattern-catalog
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake-pattern-catalog/intake-pattern-catalog-{{ version }}.tar.gz
  sha256: 68efbf9b00680b8b4cee86e6d30196ebe70a98089467cc7aa4802f591d89614e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - intake
    - requests # Remove after https://github.com/intake/intake/issues/708 is closed

test:
  imports:
    - intake_pattern_catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DTN-Public/intake-pattern-catalog
  summary: Intake plugin for specifying a file-path pattern which can represent a number of different entries
  license_file: LICENSE.md
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - raybellwaves
    - tdhopper
    - blackary
